on:
  push:
    branches: main
jobs:
    deploy_job:
     runs-on: ubuntu-latest
     name: deploy
     steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: 'chmod -R 777 storage/'

      - name: Deploy file
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
         username: 'naqaa@naqaa.app'
         server: 'naqaa.app'
         port: '21'
         server-dir: '/naqaa/'
         password: 'rEdGv+BJK8}v'
